version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=postgres
      - REDIS_ADDR=redis:6379  # ← ДОБАВЬ
      - REDIS_DB=0             # ← ДОБАВЬ
    depends_on:
      - postgres
      - redis                  # ← ДОБАВЬ
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:                        # ← ДОБАВЬ ЭТОТ СЕРВИС
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: